apps/registro/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import *


urlpatterns = [
	url(r'^$', indexRegister, name='vista_registro'),
]

flatly/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('apps.author.urls')),
]

apps/registro/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
	username = forms.CharField(label="Nombre de Usuario", widget=forms.TextInput())
	first_name = forms.CharField(label="Nombre(s)", widget=forms.TextInput())
	last_name = forms.CharField(label="Apellido(s)", widget=forms.TextInput())
	email = forms.EmailField(label="Email", widget=forms.TextInput())
	password_one = forms.CharField(label="Password", widget=forms.PasswordInput(render_value=False))
	password_two = forms.CharField(label="Confirmar Password", widget=forms.PasswordInput(render_value=False))

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			u = User.objects.get(username = username)
		except User.DoesNotExist:
			return username
		raise forms.ValidationError('Nombre de usuario ya existe.')

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			u = User.objects.get(email=email)
		except User.DoesNotExist:
			return email
		raise forms.ValidationError('Email ya registrado.')

	def clean_password_two(self):
		password_one = self.cleaned_data['password_one']
		password_two = self.cleaned_data['password_two']

		if password_one == password_two:
			pass
		else:
			raise forms.ValidationError('Password no coinciden')

apps/registro/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.http import HttpResponseRedirect

from .forms import RegisterForm


def indexRegister(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	else:
		form = RegisterForm()
		if request.method == "POST":
			form = RegisterForm(request.POST)
			if form.is_valid():
				usuario = form.cleaned_data['username']
				first_name = form.cleaned_data['first_name']
				last_name = form.cleaned_data['last_name']
				email = form.cleaned_data['email']
				password_one = form.cleaned_data['password_one']
				password_two = form.cleaned_data['password_two']
				u = User.objects.create_user(username=usuario, first_name=first_name, last_name=last_name, email=email, password=password_one)
				u.save()
				us = 'Home'
				uslink = '/'
				vs = 'Registro'
				context = {
					'us':us,
					'uslink':uslink,
					'vs':vs,
				}
				return render(request, 'registro/thanks_register.html', context)
			else:
				us = 'Home'
				uslink = '/'
				vs = 'Registro'
				context = {
					'us':us,
					'uslink':uslink,
					'vs':vs,
					'form':form,
				}
				return render(request, 'registro/index.html', context)
		us = 'Home'
		uslink = '/'
		vs = 'Registro'
		context = {
			'us':us,
			'uslink':uslink,
			'vs':vs,
			'form':form,
		}
		return render(request, 'registro/index.html', context)

templates/registro/index.html
{% extends 'base/base.html' %}

{% block title %} Registro | FlatlyBlog{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-sm-8">
			<div class="row">
				<div class="col-sm-12">
					{% include 'base/ads.html' %}
				</div>
				<div class="col-sm-12">
					{% if mensaje %}<div class="alert alert-danger" role="alert"> <strong>{{ mensaje }}</strong> </div>{% endif %}
					<h2 class="text-center"><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> Registro</h2>
					<hr>
					<form actiom="." class="form-horizontal" method="POST">
						{% csrf_token %}
						<div class="form-group">
							<label for="id_username" class="col-md-2 control-label">Usuario*</label>
							<div class="col-md-10">
								<input type="text" class="form-control" id="id_username" placeholder="Usuario*" required name="username">
							</div>
						</div>
						<div class="form-group">
							<label for="inputNombre" class="col-md-2 control-label">Nombre(s)*</label>
							<div class="col-md-10">
								<input type="text" class="form-control" id="inputNombre" placeholder="Nombre(s)*" required name="first_name">
							</div>
						</div>
						<div class="form-group">
							<label for="inputApellido" class="col-md-2 control-label">Apellido(s)</label>
							<div class="col-md-10">
								<input type="text" class="form-control" id="inputApellido" placeholder="Apellido(s)" name="last_name">
							</div>
						</div>
						<div class="form-group">
							<label for="id_email" class="col-md-2 control-label">Correo electrónico*</label>
							<div class="col-md-10">
								<input type="email" class="form-control" id="id_email" placeholder="Correo electrónico*" required name="email">
							</div>
						</div>
						<div class="form-group">
							<label for="id_password_one" class="col-md-2 control-label">Contraseña*</label>
							<div class="col-md-10">
								<input type="password" class="form-control" id="id_password_one" placeholder="Contraseña*" required name="password_one">
							</div>
						</div>
						<div class="form-group">
							<label for="id_password_two" class="col-md-2 control-label">Confirmar contraseña*</label>
							<div class="col-md-10">
								<input type="password" class="form-control" id="id_password_two" placeholder="Confirmar contraseña*" required name="password_two">
							</div>
						</div>
						<hr>
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button type="submit" class="btn btn-default">Registrarme</button>
							</div>
						</div>
					</form>
				</div>
				<div class="col-sm-12 padding-10"></div>
				<div class="col-sm-12">
					{% include 'base/ads2.html' %}
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<aside>
				{% include 'base/link.html' %}
				{% include 'base/banner.html' %}
			</aside>
		</div>
	</div>
{% endblock %}

templates/registro/thanks_register.html
{% extends 'base/base.html' %}

{% block title %} Registro - Gracias por registrarse! | FlatlyBlog{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-sm-8">
			<div class="row">
				<div class="col-sm-12">
					{% if mensaje %}<div class="alert alert-danger" role="alert"> <strong>{{ mensaje }}</strong> </div>{% endif %}
					<h2 class="text-center">Gracias por registrarse!</h2>
					<hr>
				</div>
				<div class="col-sm-12 padding-10"></div>
				<div class="col-sm-12">
					{% include 'base/ads.html' %}
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<aside>
				{% include 'base/link.html' %}
				{% include 'base/banner.html' %}
			</aside>
		</div>
	</div>
{% endblock %}

{% block licencia %}
{% endblock %}
{% block tecnologia %}
{% endblock %}